[package]
name = "mensar"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.129", features = ["derive"] }
reqwest = { version = "0.11.4", features = ["json"] }
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
textwrap = "0.14.2"
colored = "2"
clap = { version = "3.0.5", features = ["derive"] }
